const sniper = {
	dutch: `Wat heb je verdomme net over mij gezegd, kleine trut? Ik zal je laten weten dat ik aan de top van mijn Navy Seals-promotie ben geslaagd, dat ik tussenbeide ben gekomen in tal van geheime operaties tegen Al-Qaida en dat ik ongeveer 300 slachtoffers heb geleden. Ik ben getraind in guerrillaoorlogvoering en ik ben de beste sluipschutter in het Amerikaanse leger. Voor mij ben je niets meer dan een ander doel. Ik zal je van de verdomde kaart wissen met een nauwkeurigheid die nog nooit eerder op deze aarde is gezien, neem mijn verdomde woorden op. Denk je dat je ongestraft kunt blijven nadat je die dingen over mij op internet hebt verteld? Denk beter, klootzak. Op dit moment neem ik contact op met mijn geheime netwerk in de Verenigde Staten en uw IP wordt nu bijgehouden, dus bereid u voor op de storm, worm. De storm die het zielige kleine ding dat je je leven noemt, zal uitwissen. Je bent dood, jongen. Ik kan overal en altijd zijn en ik kan je op zevenhonderd verschillende manieren doden, en dat is alleen met mijn handen. Niet alleen ben ik volledig getraind in ongewapende gevechten, maar ik heb volledige toegang tot het Marine Corps van de Verenigde Staten en ik zal ze gebruiken om je ellendige kont van het gezicht van het continent te wissen, kleine shit. Als je de verdomde vergelding had gekend die je kleine en "intelligente" commentaar je zou brengen, zou je nog steeds je verdomde mond hebben gesloten. Maar je kon het niet, je deed het niet en nu betaal je de prijs, idioot. Ik ga mijn woede op je poepen en je zult erin verdrinken. Je bent dood, jochie.`,

	spanish: `¿Qué cojones acabas de decir de mi, putita? Te haré saber que me gradué en lo más alto de mi promoción en los Navy Seals, he intervenido en numerosas operaciones secretas contra Al-Qaeda, y tengo alrededor de 300 bajas confirmadas. Estoy entrenado en guerra de guerrillas y soy el mejor francotirador del ejército de EE.UU.. ¿Tú? Para mi no eres nada más que otro objetivo. Te borraré del puto mapa con una precisión que jamás se ha visto antes en esta Tierra, graba mis putas palabras. ¿Crees que puedes salir impune después de contar esas mierdas sobre mi en internet? Piénsatelo mejor, cabrón. Mientras hablamos estoy contactando con mi red secreta a través de los Estados Unidos y tu IP está siendo rastreada ahora mismo, así que ve preparándote para la tormenta, gusano. La tormenta que va a borrar la patética cosita que llamas tu vida. Estás muerto, niño. Puedo estar en cualquier parte, en cualquier momento, y puedo matarte de unas setecientas maneras distintas, y eso es sólo con mis manos. No solo estoy totalmente entrenado en combate desarmado, sino que tengo pleno acceso a los Cuerpos de Marines de los Estados Unidos y voy a usarlos para borrar tu miserable culo de la faz del continente, mierdecilla. Si pudieras haber sabido la maldita retribución que te iba a traer tu pequeño e "inteligente" comentario, igual habrías cerrado tu puta boca. Pero no pudiste, no lo hiciste y ahora estás pagando el precio, puto idiota. Voy a cagar mi furia sobre tí y te vas a ahogar en ella. Estás muerto, chaval.`,

	cthulu: `Ahf' fuck ymg' mgepah ahehyee fucking yog ai ya, ymg' little bitch? Y''ll mgep ymg' Y' kadishtu graduated top ot ya class ph'nglui navy seals, ng Y''ve mgepah involved ph'nglui numerous r'luh raids llll al-quaeda, ng Y' mgep ph' 300 confirmed ah'n'gha. Y' ah trained ph'nglui gorilla ah'n'ghayar ng Y''m top sniper ph'nglui entire c' armed forces. Ymg' ah soth l' ya mgng ahehyee ehyeahog target. Y' ephaiwipe ymg' fuck yog llll precision likes ot hh' mgep mgsyha'h mgepah seen mgep llll fahf shugg, mark ya fucking aimgr'luhh. Ymg' ahlloig ymg' ahor get mglagln llll ai cahf shit l' ya ph' internet? ahlloig ephaii, fucker. Iiahe c' Y' ai ah shtunggli ya r'luh network ot spies ph' usa ng ymg' ip ah being traced right hai l' ymg' vulgtmnahor prepare llll storm, maggot. The storm cahf wipes yog pathetic little hnah ymg' ymg' uln lw'nafh. Ymg''re fucking mglw'nafh, kid. Y' ahor ah anywhere, anytime, ng Y' ahor ymg' ah'n'gha ph'nglui ph' yeeogngm yeeogogng ways, ng cahf's ahehyee llll ya bare bthnknahorr. Nafl uh'eor Y' ah extensively trained ph'nglui unarmed combat, mgng Y' mgep access l' entire arsenal ot united states marine corps ng Y' h' ephaiahuaaah l' h' full extent l' wipe ymg' miserable ass naIIII ot ahororr'e continent, ymg' little shit. If uh'eor ymg' ahor mgep mgepkadishtu ahf' mgvulgtmoth retribution ymg' little "clever" comment yog mgepah l' tharanak mgyogor l' ymg', maybe ymg' would mgep ymg' mgepah'f'nah fucking tongue. Mgng ymg' couldn't, ymg' didn't, ng hai ymg''re paying price, ymg' goddamn legeth'drn. Y' ephaishit fury nilgh'ri ph' ymg' ng ymg' ephaidrown ph'nglui h'. Ymg''re fucking mglw'nafh, kiddo`,

	scp: `What the [REDACTED] did you just [REDACTED] do to me, Dr. Wright? I’ll have you know I am made using only the finest, carefully selected oats in General Mills, and I’ve been involved in numerous secret containment breaches and I have over 300 confirmed [REDACTED]. I am trained in fueling people until lunch and I’m the top SCP under the entire Foundation. You are nothing to me but just another non-anomalous piece of [REDACTED]. I will wipe you the [REDACTED] out with a breakfast the likes of which has never been seen before in this Multiverse, mark my [REDACTED] words. You think you can get away with ripping that flappy lid thing on me trying to eat breakfast? Think again, [REDACTED]. As we speak I am contacting my secret network of spies across the Foundation and your IP is being traced right now so you better prepare for the storm, Wright. The storm that wipes out the pathetic little thing you call your life. You’re [REDACTED] dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that’s just with my contents. Not only am I extensively trained in creating quality breakfasts, but I have access to the entire arsenal of the Chaos Insurgency and I will use it to its full extent to wipe your miserable green ass-shaped hair off the face of the continent, you little [REDACTED]. If only you could have known what unholy retribution your little “accident” was about to bring down upon you, maybe you would have been more careful. But you couldn’t, you didn’t, and now you’re going to pay the price, you goddamn idiot. I will [REDACTED] fury all over you and you will drown in it. You’re [REDACTED] dead, Doctor.`,

	oldeEnglish: `What the alas didst thee just fucking sayeth about me, thee dram wench? i'll has't thee knoweth i graduat'd top of mine own class in the navy seals, and i've been involv'd in num'rous secret raids on al-quaeda, and i has't ov'r 300 confirm'd kills. I am did train in g'rilla warfare and i'm the top snip'r in the entire us cap-a-pe f'rces. Thou art nothing to me but just anoth'r targeteth. I shall wipeth thee the alas out with precision the likes of which hast nev'r been seen bef're on this earth, marketh mine own fucking w'rds. Thee bethink thee can receiveth hence with declaring yond the horror to me ov'r the int'rnet? bethink again, alas'r. As we speaketh i am contacting mine own secret netw'rk of spies across the usa and thy ip is being trac'd even but now so thee bett'r prepareth f'r the st'rm, maggot. The st'rm yond wipes out the pathetic dram thing thee calleth thy life. Thou art fucking dead, peat. I can beest anywh're, anytime, and i can killeth thee in ov'r seven hundr'd ways, and yond's just with mine own bareth hands. Not only am i extensively did train in unarm'd combat, but i has't access to the entire arsenal of the unit'd states marine c'rps and i shall useth t to its full extent to wipeth thy mis'rable rampallian off the visage of the continent, thee dram the horror. If 't be true only thee couldst has't known what unholy retribution thy dram "clev'r" comment wast about to bringeth down upon thee, haply thee wouldst has't did hold thy fucking tongue. But thee couldn't, thee didn't, and anon thou art paying the price, thee goddamn clotpole. I shall the horror fury all ov'r thee and thee shall drowneth in t. Thou art fucking dead, kiddo`,

	aussie: `˙ǝʇɐɯ 'pɐǝp ƃuᴉʞɔnɟ ǝɹ’no⅄ ˙ʇᴉ uᴉ uʍoɹp ɐuuoƃ ǝɹ’noʎ puɐ ɐʎ ɹǝʌo llɐ ʎɹnɟ ʇᴉɥs llᴉʍ I ˙ǝʇɐɯ 'ǝɔᴉɹd ǝɥʇ ƃuᴉʎɐd ǝɹ’noʎ ʍou puɐ 'ʇ’upᴉp ɐʎ 'ʇ’uplnoɔ ɐʎ ʇnq ˙ǝnƃuoʇ ƃuᴉʞɔnɟ ɹnoʎ plǝɥ ɐplnoʍ ɐʎ ǝqʎɐɯ 'ɐʎ uodn uʍop ƃuᴉɹq ɐʇ ʇnoqɐ sɐʍ ʇɐɥɔʞɔɐq ”ɹǝʌǝlɔ“ ǝlʇʇᴉl ɹnoʎ ʇᴉɥsllnq ʇɐɥʍ uʍouʞ ɐplnoɔ ɐʎ ʎluo ɟI ˙ʞɔᴉɹd noʎ 'ʞɔɐqʇno ǝɥʇ ɟo ʇno ɹoɟ ɐʎ ʇᴉɥ oʇ ʇuǝʇxǝ llnɟ sʇᴉ oʇ ʇᴉ ǝsn llᴉʍ I puɐ punoɹפ ʇǝʞɔᴉɹƆ ǝuɹnoqlǝW ǝɥʇ ɟo sʇɐq ʇǝʞɔᴉɹɔ ɟo pǝɥs ǝɹᴉʇuǝ ǝɥʇ oʇ ssǝɔɔɐ ǝʌɐɥ I ʇnq 'sʞɔᴉɹd ƃuᴉddoɹp uᴉ pǝuᴉɐɹʇ ʎlǝʌᴉsuǝʇxǝ I ɯɐ ʎluo ʇoN ˙ʇɐq ʇǝʞɔᴉɹɔ ɐ puɐ qΛ ɟo ǝlʇʇoq pǝɥsɐɯs ʎq ɥʇᴉʍ ʇsnɾ s’ʇɐɥʇ puɐ 'sʎɐʍ pǝɹpunɥ uǝʌǝs ɹǝʌo uᴉ noʎ doɹp uɐɔ I puɐ 'ǝɯᴉʇʎuɐ 'ǝɹǝɥʍʎuɐ ǝq uɐɔ I ˙ʞɔᴉɹd 'pɐǝp ƃuᴉʞɔnɟ ǝɹ’no⅄ ˙ǝɟᴉl ɹnoʎ llɐɔ ɐʎ ƃuᴉɥʇ ǝlʇʇᴉl ɔᴉʇǝɥʇɐd ǝɥʇ ʇno sǝdᴉʍ ʇɐɥʇ ɹǝpunɥʇ ǝɥ┴ ˙ǝʇɐɯ 'ɹǝpunɥʇ ǝɥʇ ɹoɟ ǝɹɐdǝɹd ɹǝʇʇǝq ɐʎ os ʍou ʇɥƃᴉɹ pǝɔɐɹʇ ƃuᴉǝq sᴉ ԀI ɹnoʎ puɐ ǝɔᴉloԀ lɐɹǝpǝℲ uɐᴉlɐɹʇsn∀ ǝɥʇ puɐ llnquɹn┴ ɯloɔlɐW ƃuᴉʇɔɐʇuoɔ ɯɐ I ʞɐǝds ǝʍ s∀ ˙ǝʇɐɯ 'uᴉɐƃɐ ʞuᴉɥ┴ ¿ʇǝuɹǝʇuI ǝɥʇ ɹǝʌo ǝɯ oʇ ʇᴉɥsllnq ʇɐɥʇ ƃuᴉʎɐs ɥʇᴉʍ ʎɐʍɐ ʇǝƃ uɐɔ ɐʎ ʞuᴉɥʇ ɐ⅄ ˙ǝʇɐɯ 'spɹoʍ ƃuᴉʞɔnɟ ʎɯ ʞɹɐɯ 'ɥʇɹɐƎ sᴉɥʇ uo ǝɹoɟǝq pǝɥsɐɯs uǝǝq ɹǝʌǝu sɐɥ ɥɔᴉɥʍ ɟo sǝʞᴉl ǝɥʇ sǝlʇʇoq qΛ ɥʇᴉʍ ʇno ʞɔnɟ ǝɥʇ ɐʎ doɹp llᴉʍ I ˙uɐɟ pooʍƃuᴉlloƆ ɐ ʇnq ǝɯ oʇ ƃuᴉɥʇou ǝɹɐ no⅄ ˙uoʇlɹɐƆ ɟo ʎʇᴉɔ ǝɹᴉʇuǝ ǝɥʇ uᴉ ɹǝʇɐǝ ƃɐus doʇ ǝɥʇ ɯɐ I puɐ sǝɹᴉdɯn spɹɐʍoʇ ǝsnqɐ lɐɔoʌ uᴉ pǝuᴉɐɹʇ ɯɐ I ˙ʞunɹp XXXX ɟo sqɐls 00Ɛ ɹǝʌo ǝʌɐɥ I puɐ 'uoʇlɹɐƆ uᴉ sʇsǝʇuoɔ ƃuᴉllnɔs ɹǝǝq snoɹǝɯnu uᴉ pǝʌloʌuᴉ uǝǝq ǝʌ’I puɐ 'ʎɯɹ∀ uɐᴉlɐɹʇsn∀ ǝɥʇ uᴉ ssɐlɔ ʎɯ ɟo doʇ pǝʇɐnpɐɹƃ I ʍouʞ ɐʎ ǝʌɐɥ ll’I ¿ǝʇɐɯ 'ǝɯ llɐɔ ʇsnɾ ɐɾpᴉp ʇɐɥM`,

	pirate: `What in Davy Jones' locker did ye just bark at me, ye scurvy bilgerat? I'll have ye know I be the meanest cutthroat on the seven seas, and I've led numerous raids on fishing villages, and raped over 300 wenches. I be trained in hit-and-run pillaging and be the deadliest with a pistol of all the captains on the high seas. Ye be nothing to me but another source o' swag. I'll have yer guts for garters and keel haul ye like never been done before, hear me true. You think ye can hide behind your newfangled computing device? Think twice on that, scallywag. As we parley I be contacting my secret network o' pirates across the sea and yer port is being tracked right now so ye better prepare for the typhoon, weevil. The kind o' monsoon that'll wipe ye off the map. You're sharkbait, fool. I can sail anywhere, in any waters, and can kill ye in o'er seven hundred ways, and that be just with me hook and fist. Not only do I be top o' the line with a cutlass, but I have an entire pirate fleet at my beck and call and I'll damned sure use it all to wipe yer arse off o' the world, ye dog. If only ye had had the foresight to know what devilish wrath your jibe was about to incur, ye might have belayed the comment. But ye couldn't, ye didn't, and now ye'll pay the ultimate toll, you buffoon. I'll take a dump fury all over ye and ye'll drown in the depths o' it. You're fish food now.`,

	potter: `What the leviosá did you just say about me, you little mudblood? I’ll have you know I graduated top of my class in the hogwarts school, and I’ve been involved in numerous secret raids on Harry Potter, and I have died over 7 times. I am trained in the dark arts and I’m the top in the class in the entire school. You are nothing to me but just another little baby to kill me. I will wig you the heck out with spells the likes of which has never been seen before on this Earth, mark my words. You think you can get away with saying that hogwash to me over the Internet? Think again, Dumbledore. As we speak in Parseltogue, I am contacting my secret network of Death Eaters and witches across the Earth and your bedroom closet is being traced right now so you better prepare for the spell, Potter. My name that spooks the pathetic little thing you call your wits. You’re hecka spooked, kid. I can kill anywhere, anytime, and I can kill you in over seven hundred ways, and that’s just with my wand. Not only am I extensively trained in the dark arts, but I have access to the entire colony of the Death Eaters and I will use it to its full extent to kill your miserable butt off the face of the world, avada kedavra. If only you could have known what stupid retribution your little “clever” comment was about to bring down upon you, maybe you would have held on to your hat. But you couldn’t, you didn’t, and now you’re paying the price, you dumb little baby. I will spook Death Eaters all over you and you will drown in them. You’re dead, Potter.`,

	halloween: `What the bones did you just skellington say about me, you little smoothskin? I’ll have you know I graduated top of my class in the spooky skeletons trumpet school, and I’ve been involved in numerous secret raids on halloween, and I have over 300 confirmed doots. I am trained in scary spooking and I’m the top trumpeter in the entire spooky graveyard. You are nothing to me but just another little baby to be spooked. I will wig you the heck out with spookiness the likes of which has never been seen before on this Earth, mark my spooky words. You think you can get away with saying that hogwash to me over the Internet? Think again, spooker. As we speak I am contacting my secret network of spooky mummies and ghosts across the creepy crypt and your bedroom closet is being traced right now so you better prepare for the storm, doot. The storm that spooks out the pathetic little thing you call your wits. You’re hecka spooked, kid. I can spook anywhere, anytime, and I can spook you in over seven hundred ways, and that’s just with my trumpet. Not only am I extensively trained in spooky scaring, but I have access to the entire trumpet of the spooky skeletal abyss and I will use it to its full extent to spook your miserable butt off the face of the continent, doot doot doot. If only you could have known what spooky retribution your little “clever” comment was about to bring down upon you, maybe you would have held on to your hat. But you couldn’t, you didn’t, and now you’re paying the price, you dumb little baby. I will spook skellingtons all over you and you will drown in them. You’re spooked, kiddo.`,
}

randomSniper = () => {
	let sniperArr = [
		sniper.aussie,
		sniper.cthulu,
		sniper.dutch,
		sniper.halloween,
		sniper.oldeEnglish,
		sniper.pirate,
		sniper.potter,
		sniper.scp,
		sniper.spanish,
	]
	return sniperArr[Math.floor(Math.random() * sniperArr.length)]
}

module.exports = { randomSniper, sniper }
